
services:

  ########### COMPONENT TRACING

  Graviton\CommonBundle\Component\Tracing\TracingListener:
    tags:
      - { name: kernel.event_subscriber }

  Graviton\CommonBundle\Component\Tracing\DoctrineODMTracingListener:
    tags:
      - { name: doctrine_mongodb.odm.event_subscriber }
