imports:
  - { resource: services_cache.yml }
  - { resource: services_deployment.yml }
  - { resource: services_doctrine.yml }
  - { resource: services_http.yml }
  - { resource: services_session.yml }
  - { resource: services_tracing.yml }
  - { resource: services_redis.yml }
  - { resource: services_audit.yml }
  - { resource: services_logging.yml }
