
services:

  ########### COMPONENT HTTP

  Graviton\CommonBundle\Component\Http\Listener\CorsResponseListener:
    arguments:
      - '%graviton.common.http.cors.headers_allowed%'
      - '%graviton.common.http.cors.headers_exposed%'
      - '%graviton.common.http.cors.methods_allowed%'
      - '%graviton.common.http.cors.origins_allowed%'
      - '%graviton.common.http.cors.origins_credentials_allowed%'
    tags:
      - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
