
services:

  ########### COMPONENT SESSION

  Graviton\CommonBundle\Component\Session\Factory:
    arguments:
      - '@Graviton\CommonBundle\Component\Redis\OptionalRedis'
      - '@session.handler.native_file'

  graviton.common.session:
    class: Symfony\Component\HttpFoundation\Session\Storage\Handler\AbstractSessionHandler
    factory: ['@Graviton\CommonBundle\Component\Session\Factory', 'getInstance']
