
services:

  ########### COMPONENT CACHE

  Graviton\CommonBundle\Component\Cache\Factory:
    arguments:
      - '@cache.app'
      - "%graviton.common.cache.instance_id%"
      - "%graviton.common.cache.adapter_override%"
      - '@logger'
      - '@Graviton\CommonBundle\Component\Redis\OptionalRedis'

  graviton.common.cache.adapter.app:
    class: Psr\Cache\CacheItemPoolInterface
    factory: ['@Graviton\CommonBundle\Component\Cache\Factory', 'getInstance']

  graviton.common.lockingcache.adapter.app:
    class: Graviton\CommonBundle\Component\Cache\ExclusiveLockingCache
    arguments:
      - '@graviton.common.cache.adapter.app'
      - '@graviton.common.lock.app'

  # this is a cache for stuff to cache *locally* that does not change - items should never expire! goes through opcache..
  graviton.common.cache.adapter.static:
    class: Symfony\Component\Cache\Adapter\PhpFilesAdapter
    arguments:
      - static-cache
      - 0
      - '%kernel.cache_dir%/'

  # commands
  Graviton\CommonBundle\Component\Cache\Command\ClearRedisCommand:
    tags:
      - { name: console.command }
    arguments:
      - '@graviton.common.cache.adapter.app'
