
services:

  Graviton\CommonBundle\Component\Tracing\DoctrineODMTracingListener:
    arguments:
      - '@auxmoney_opentracing'
    tags:
      - { name: doctrine_mongodb.odm.event_subscriber }

  Graviton\CommonBundle\Component\Tracing\StopwatchFactory: ~

  graviton.common.stopwatch:
    class: 'Symfony\Component\Stopwatch\Stopwatch'
    factory: ['@Graviton\CommonBundle\Component\Tracing\StopwatchFactory', 'getInstance']
