services:

  Graviton\DocumentBundle\Command\DocumentIndexesCommand:
    arguments:
      - "@logger"
      - "@doctrine_mongodb.odm.default_document_manager"
    tags:
      - { name: console.command }
      - { name: mongodb_dependent }
