
services:

  ########### COMPONENT DEPLOYMENT

  ## version information
  Graviton\CommonBundle\Component\Deployment\VersionInformation:

  ## commands

  Graviton\CommonBundle\Component\Deployment\Command\CheckDeploymentCommand:
    tags:
      - { name: console.command }
      - { name: mongodb_dependent }
    arguments:
      - "@=service(parameter('graviton.common.mongo_document_manager_service_id'))"
      - '%graviton.common.deployment.check_package_name%'

  Graviton\CommonBundle\Component\Deployment\Command\WaitForDatabaseCommand:
    arguments:
      - "@=service(parameter('graviton.common.mongo_document_manager_service_id'))"
    tags:
      - { name: console.command }
      - { name: mongodb_dependent }

  Graviton\CommonBundle\Component\Deployment\Command\PrepareMongoIndexesCommand:
    arguments:
      - "@=service(parameter('graviton.common.mongo_document_manager_service_id'))"
    tags:
      - { name: console.command }
      - { name: mongodb_dependent }
